#!/bin/bash
if [ $(which pkexec) ]; then
	pkexec --disable-internal-agent \
	env DISPLAY="$DISPLAY" \
	    XAUTHORITY="$XAUTHORITY" \
	    DBUS_SESSION_BUS_ADDRESS="$DBUS_SESSION_BUS_ADDRESS" \
	    HOME="$HOME" \
	    "/usr/bin/calamares" "-D6" "$@"
else
	/usr/bin/calamares "-D6" "$@"
fi
